/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        tertiary: '#aaffdc',
        'on-primary': '#005762',
        secondary: '#a68cff',
        'on-primary-fixed': '#003840',
        'secondary-fixed-dim': '#cabaff',
        'tertiary-dim': '#00edb4',
        'surface-container-high': '#141f38',
        'error-container': '#9f0519',
        'surface-variant': '#192540',
        'on-background': '#dee5ff',
        'on-primary-container': '#004d57',
        'inverse-on-surface': '#4d556b',
        'on-surface-variant': '#a3aac4',
        'inverse-primary': '#006976',
        'surface-container-lowest': '#000000',
        'on-tertiary-container': '#005c44',
        'secondary-fixed': '#d8caff',
        'surface-container': '#0f1930',
        'secondary-dim': '#7e51ff',
        'surface-dim': '#060e20',
        'primary-container': '#00e3fd',
        'surface-tint': '#81ecff',
        'on-secondary-fixed-variant': '#591bdc',
        'on-secondary': '#25006b',
        'on-error-container': '#ffa8a3',
        primary: '#81ecff',
        background: '#060e20',
        'on-surface': '#dee5ff',
        'surface-bright': '#1f2b49',
        'on-tertiary-fixed': '#004734',
        error: '#ff716c',
        outline: '#6d758c',
        'on-tertiary': '#00654b',
        surface: '#060e20',
        'on-secondary-fixed': '#3b00a0',
        'outline-variant': '#40485d',
        'on-tertiary-fixed-variant': '#00664c',
        'on-secondary-container': '#e4daff',
        'primary-fixed-dim': '#00d4ec',
        'error-dim': '#d7383b',
        'inverse-surface': '#faf8ff',
        'tertiary-container': '#00fdc1',
        'tertiary-fixed': '#00fdc1',
        'on-error': '#490006',
        'primary-dim': '#00d4ec',
        'primary-fixed': '#00e3fd',
        'tertiary-fixed-dim': '#00edb4',
        'surface-container-low': '#091328',
        'surface-container-highest': '#192540',
        'secondary-container': '#591adc',
        'on-primary-fixed-variant': '#005762',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
